sudo: false
language: go
go:
  - 1.11.x
install:
  - go mod download
script:
  - go test ./... -v
  - GOOS=linux GOARCH=amd64 go build -o nancy-linux.amd64-${VERSION}
  - GOOS=darwin GOARCH=amd64 go build -o nancy-darwin.amd64-${VERSION}
  - GOOS=windows GOARCH=amd64 go build -o nancy-windows.amd64-${VERSION}
env:
  - GO111MODULE=on
  - VERSION=0.0.1
